### ISSUE TITLE
BRAT Installation fails "main.js missing from release"

### ISSUE THREAD

**Issue by universemaster** [RyotaUshio/obsidian-math#118]
I'm aware of the warning "WARNING: The following instruction is for installing ver. 0.2.1, which is older than the unreleased latest version of this plugin that this documentation is written for."

However, if BRAT installation instructions exist, I would have expected them to work.

**Comment by RyotaUshio** [comment]
Thank you a lot for reporting!
I tried on the sandbox vault and was able to reproduce the error.
I fixed `manifest.json`, and now it should all be fine. Could you try again?

**Comment by RyotaUshio** [comment]
By the way, I noticed that the default language is set to Japanese in the latest release. 
Please update it to English in the plugin settings, if you need to.
