### ISSUE TITLE
Clever referencing Display Function Only Works for Theorems

### ISSUE THREAD

**Issue by LynetteCullens** [RyotaUshio/obsidian-math#221]
First of all, I apologize if I'm not using the proper using the proper template. I couldn't find one.
Issue: I can't get the Display function of Clever referencing to work with any callout but a Theorem.
![display function edit 2](https://github.com/RyotaUshio/obsidian-latex-theorem-equation-referencer/assets/45722611/1e861327-b5c0-4c0f-8440-827a69f84501)

Works:
`# Links
Link to $\frac{{\color{red}q}_{\color{yellow}x}}{\color{blue}A}=-{\color{purple}k}\frac{d{\color{black}T}}{d{\color{yellow}x}} \tag{15-1}$: [[#^8xih4x]]
> [!theorem] Fourier Equation
> %% display: $\scriptsize\frac{{\color{red}q}_{\color{yellow}x}}{\color{blue}A}=-{\color{purple}k}\frac{d{\color{black}T}}{d{\color{yellow}x}} \tag{15-1}$ %%
> #Cartesian_Coordinates #One-dimensional_form #Equation
> $$
 \frac{{\color{red}q}_{\color{yellow}x}}{\color{blue}A}=-{\color{purple}k}\frac{d{\color{black}T}}{d{\color{yellow}x}} \tag{15-1}
>$$
>
>${\Large\color{red}\blacksquare}=$ Heat Flow Rate  
${\Large\color{yellow}\blacksquare}=$ In the x-direction  
${\Large\color{blue}\blacksquare}=$ Area (Corresponding to x-direction)  
${\Large\color{purple}\blacksquare}=$ Thermal Conductivity (Negative because q is in direction of negative $\scriptsize\Delta T$ **<span style="font-weight:bold; color:#ff0000">Hot</span>** $\rightarrow$ **<span style="font-weight:bold; color:#021ff7">Cold</span>**  
>
>$\frac{⬛}{🟨}=$ Temperature Gradient 
^8xih4x
 
[[#^8xih4x]]`

Does Not Work:

`# Links
Link to $\frac{{\color{red}q}_{\color{yellow}x}}{\color{blue}A}=-{\color{purple}k}\frac{d{\color{black}T}}{d{\color{yellow}x}} \tag{15-1}$: [[#^8xih4x]]
> [!equation] Fourier Equation
> %% display: $\scriptsize\frac{{\color{red}q}_{\color{yellow}x}}{\color{blue}A}=-{\color{purple}k}\frac{d{\color{black}T}}{d{\color{yellow}x}} \tag{15-1}$ %%
> #Cartesian_Coordinates #One-dimensional_form #Equation
> $$
 \frac{{\color{red}q}_{\color{yellow}x}}{\color{blue}A}=-{\color{purple}k}\frac{d{\color{black}T}}{d{\color{yellow}x}} \tag{15-1}
>$$
>
>${\Large\color{red}\blacksquare}=$ Heat Flow Rate  
${\Large\color{yellow}\blacksquare}=$ In the x-direction  
${\Large\color{blue}\blacksquare}=$ Area (Corresponding to x-direction)  
${\Large\color{purple}\blacksquare}=$ Thermal Conductivity (Negative because q is in direction of negative $\scriptsize\Delta T$ **<span style="font-weight:bold; color:#ff0000">Hot</span>** $\rightarrow$ **<span style="font-weight:bold; color:#021ff7">Cold</span>**  
>
>$\frac{⬛}{🟨}=$ Temperature Gradient 
^8xih4x
 
[[#^8xih4x]]`

**Comment by RyotaUshio** [comment]
This is because `> [!theorem]` is a callout type supported by this plugin while `> [!equation]` is not.

From the [documentation](https://ryotaushio.github.io/obsidian-latex-theorem-equation-referencer/theorem-callouts/theorem-callouts.html), the supported callout types are:

> Here's the complete list of available environments and aliases.
> 
> | Environment name | Alias |
> | ---------------- | ----- |
> | axiom            | axm   |
> | definition       | def   |
> | lemma            | lem   |
> | proposition      | prp  |
> | theorem          | thm   |
> | corollary        | cor   |
> | claim            | clm   |
> | assumption       | asm   |
> | example[^1]          | exm   |
> | exercise         | exr   |
> | conjecture       | cnj   |
> | hypothesis       | hyp   |
> | remark           | rmk   |
> 
> [^1]: `> [!example]` conflicts with [Obsidian's built-in callout type](https://help.obsidian.md/Editing+and+formatting/Callouts#Supported%20types). There is a setting called `Don't treat "> [!example]" as a theorem callout`, and if it's turned on, an "example" theorem callout can be inserted only with the alias syntax `> [!exm]`.

**Comment by RyotaUshio** [comment]
To reference equations, you don't have to wrap them in callouts. Something like this will work:

```
$$
f(x)
$$
^block-id

[[^block-id]]
```

For more details, see the guides on this page:

https://ryotaushio.github.io/obsidian-latex-theorem-equation-referencer/equations.html

**Comment by LynetteCullens** [comment]
> This is because `> [!theorem]` is a callout type supported by this plugin while `> [!equation]` is not.
> 
> From the [documentation](https://ryotaushio.github.io/obsidian-latex-theorem-equation-referencer/theorem-callouts/theorem-callouts.html), the supported callout types are:
> 
> > Here's the complete list of available environments and aliases.
> > 
> > 
> > 
> > Environment name
> > Alias
> > 
> > 
> > 
> > 
> > axiom
> > axm
> > 
> > 
> > definition
> > def
> > 
> > 
> > lemma
> > lem
> > 
> > 
> > proposition
> > prp
> > 
> > 
> > theorem
> > thm
> > 
> > 
> > corollary
> > cor
> > 
> > 
> > claim
> > clm
> > 
> > 
> > assumption
> > asm
> > 
> > 
> > example[1](#user-content-fn-1-d58cf3d9f0bd119aa885b963ddc39178)
> > exm
> > 
> > 
> > exercise
> > exr
> > 
> > 
> > conjecture
> > cnj
> > 
> > 
> > hypothesis
> > hyp
> > 
> > 
> > remark
> > rmk
> 
> ## Footnotes
> 1. `> [!example]` conflicts with [Obsidian's built-in callout type](https://help.obsidian.md/Editing+and+formatting/Callouts#Supported%20types). There is a setting called `Don't treat "> [!example]" as a theorem callout`, and if it's turned on, an "example" theorem callout can be inserted only with the alias syntax `> [!exm]`. [↩](#user-content-fnref-1-d58cf3d9f0bd119aa885b963ddc39178)

Thank you for the quick reply and quick solution. I appreciate it. Works perfectly now. I didn't realize. I just assumed it would work.
And Also, thank you for the updated doc. I'm assuming that you updated it recently because I don't remember it being that long in January.

**Comment by RyotaUshio** [comment]
In fact, I didn't 😃 [The last update was Dec 2023](https://github.com/RyotaUshio/obsidian-latex-theorem-equation-referencer-docs).

Glad it worked for you!
