### ISSUE TITLE
Suggestion for Enhancement: Auto-Suggest whole Equations

### ISSUE THREAD

**Issue by BananenRitter** [RyotaUshio/obsidian-math#229]
# Usecase:
Im a beginner and sure i can invest a lot of time to learn the basics but it would be much easier to use autocompletion of generic examples and fit them together.
To create a library by myself also seems too tome consuming if you think about that thousands of students have to do this. The time they waste writing basic stuff could be invested in actually solving equations.

# How does it work?
- Suggests whole Equations by:
1. using specific hotkey
2. or typing specific symbol combination
3. or Typing $, $$

- Suggestions are displayed below the currently active line.
- Occupies 3 rows vertically
- **First row** for the name of the Equation
- Shows the Suggestions 2 Times **vertically**:
1. **Second row:** As LaTeX Text
5. **Third row:** As rendered LaTeX Equation

- Search Equation by Name
- Search Equation by Major/ Topic

## Settings:
- Amount of Suggestions that are displayed at the same time **Horizontally** Values: 0-3, Standard: 1

**Comment by RyotaUshio** [comment]
I'm not sure if I understand your suggestion. Do you mean something like if I trigger the autocompletion with a query "pythagorean", several equations including $a^2 + b^2 = c^2$ are suggested?
And the suggested equations are retrieved from some library that will be included in this plugin, right?

**Comment by RyotaUshio** [comment]
> Im a beginner and sure i can invest a lot of time to learn the basics

The basic of what? LaTeX? If so, I strongly suggest just learning it. You will definitely need the skill to get a degree in STEM or related fields.

**Comment by RyotaUshio** [comment]
I found you randomly posting issues with identical content to several plugin repositories just because they are related to math or latex. Stop doing things like that. What if all the plugins implemented the same functionality independently? Also, both quick latex and latex suite are made for those who are (or are willing to be) familiar with latex and want to type equations fast, and thus they don't fit the functionality you suggest IMO.
I'd suggest you post your idea to the plugin ideas category of the official forum: https://forum.obsidian.md/c/plugins/10

**Comment by BananenRitter** [comment]
1. Well ive tried to adress the pulgins that are closest to my idea personally in order to avoid the creation of another new math plugin because i think having more plugins rather decreases the perfomance of obsidian overall.
Also some plugins are updated more frequently than others.

2. Like i said: i want to make Obsidian LaTeX more userfriendly in order for beginners to solve equations rather than learning the structure. Also learning structures is more difficut if you dont have an example that you can look at right away. Searching good sources also takes time that could be spent working. Yes searching is also a skill to learn but not the primary work you normally do.

I am not talking about simple short equations like $a^2+b^2=c^2$ but rather long ones like:
$$\large\lambda_{2}=-2:\,\,\,\,\,ker(B+2I)=ker\begin{pmatrix}
1&0&-1 \\
1&1&3 \\
0&0&0
\end{pmatrix}=
ker\begin{pmatrix}
1&0&-1 \\
0&1&4 \\
0&0&0
\end{pmatrix}=
\Bigg\{\nu\times\begin{pmatrix}
1 \\
-4 \\
1
\end{pmatrix}\Bigg|\nu\in\mathbb{R}\Bigg\}.$$

(Obviously thats not an example of an abstract equation)

and the ones that make use of all the special structures like \matrix or \align\
