### ISSUE TITLE
[BUG] Incorrect rendering of symbols in callouts & blockquotes

### ISSUE THREAD

**Issue by howwhenz** [RyotaUshio/obsidian-math#240]
Hello,

Live preview of the multi-line math block in callouts & blockquotes rendered incorrectly if the line starts with certain symbols (`+`, `-`, `*`, `/`, `=`, `'`, etc):

![image](https://github.com/user-attachments/assets/b7164094-7135-430c-80ab-8483888be512)

![image](https://github.com/user-attachments/assets/c5427fe0-6faa-43d7-a045-1ebe1c5e1e68)

It seems like that:

```text
> $$
> [Certain symbols][The rest]
> $$
```

would be rendered as:

```text
[Certain symbols]>[Certain symbols][The rest]
```

With another plugin by the same author [Better Math in Callouts & Blockquotes](https://github.com/RyotaUshio/obsidian-math-in-callout) alone can render them correctly, but if with the current plugin installed at the same time, this issue shows up.

**Environment:**
- Obsidian v1.6.7 on Windows 11
- Plugins:
    - Better Math in Callouts & Blockquotes: 0.3.7
    - LaTeX-like Theorem & Equation Referencer for Obsidian: 2.2.0

**Comment by LynetteCullens** [comment]
> math block in callouts & blockquotes rendered incorrectly if the line starts with certai
**With Render Equation Enabled**
![Live Preview with REnder Links](https://github.com/user-attachments/assets/88f8b6e0-275a-400f-8015-fe2a24b6f4ef)

It renders correctly in Live Preview when outside of the callout.

**Disable Render Equation**

![Live Preview without REnder Links](https://github.com/user-attachments/assets/71540da2-bfe2-444f-9277-852a052776f5)
**In My Vault**
![image](https://github.com/user-attachments/assets/e79588c5-f270-4969-8885-3ee782eaef76)
![image](https://github.com/user-attachments/assets/251c1db2-9d9b-40cc-8544-2ea92ae2739d)


I have the setting turned off, but I can't determine what plugin is rendering the math for me instead.

**Comment by howwhenz** [comment]
Thank you very much, it works in my vault. However, I turned off the option "Render equations inside callouts & add multi-line equation support to blockquotes" instead of "Render equation."

![image](https://github.com/user-attachments/assets/849a60af-fe60-4851-a503-968a920f5abe)

I think the "Better Math in Callouts & Blockquotes" plugin takes over live preview rendering if this option turned off.
