### ISSUE TITLE
Plugin fails to load on iPadOS

### ISSUE THREAD

**Issue by lwzbr** [RyotaUshio/obsidian-math#247]
Exactly as described in the title. I am unable to enable the plugin in iPadOS 18.1. I think this issue is due to the iPadOS update, I don’t recall having problems with iPadOS 18.0 or iPadOS 17.x

Download my repro vault here: https://www.dropbox.com/scl/fi/314fqwqcfcp8ej13fyybk/iOS-Math-booster-Vault.zip?rlkey=9d5gcm68jjra0fqnk1dokkncu&st=br4eza4s&dl=0

SYSTEM INFO:
	Operating system: ios 18.1 (Apple iPad13,16)
	Obsidian version: 1.7.4 (167)
	API version: v1.7.4
	Login status: logged in
	Language: en
	Catalyst license: none
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 1
		1: MathLinks v0.5.3

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by lwzbr** [comment]
Sorry about the double post, but i have an update. Interestingly, while the plugin cannot load from the plugin screen, it’s possible to force it to load by going to the “plugin store” and enabling it there. When this happens, certain features of the plugin do work, such as equation numbering, but it fails to recognize theorem-type callouts.

**Comment by RyotaUshio** [comment]
Thank you for the report. Some people have reported that this plugin properly loads if you have the "quick preview" plugin installed. Could you try this?

**Comment by lwzbr** [comment]
> Thank you for the report. Some people have reported that this plugin properly loads if you have the "quick preview" plugin installed. Could you try this?

I did, it fixed both the enabling issue in the main post as well as the issue with theorem callouts. Thanks.

**Comment by LynetteCullens** [comment]
> Thank you for the report. Some people have reported that this plugin properly loads if you have the "quick preview" plugin installed. Could you try this?

Are you going to add Quick Preview to the dependencies, or is it already included in dependencies?
